name: tests

on:
  pull_request:
    paths:
    - '.github/workflows/tests.yml'
    - 'R/*'
    - 'tests/testthat/*'
  push:
    paths:
    - '.github/workflows/tests.yml'
    - 'R/*'
    - 'tests/testthat/*'

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("testthat", "here"))' # add other packages if necessary
      - name: Run tests
        run: Rscript -e 'source("tests/testthat.R")'
