name: tests

on:
  pull_request:
    paths:
    - '.github/workflows/tests.yml'
    - 'R/*'
    - 'tests/testthat/*'
  push:
    paths:
    - '.github/workflows/tests.yml'
    - 'R/*'
    - 'tests/testthat/*'

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Run tests
        run: Rscript -e "source('tests/testthat.R')"
