name: tests

on:
  pull_request:
    paths:
    - '.github/workflows/tests.yml'
    - 'R/*'
    - 'tests/testthat/*'
  push:
    paths:
    - '.github/workflows/tests.yml'
    - 'R/*'
    - 'tests/testthat/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v1
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Remove `.Rprofile`
        shell: bash
        run: |
         rm .Rprofile
                
      - uses: r-lib/actions/setup-renv@v2 # use our renv.lock
        
      - name: Run unit tests
        run: source("tests/testthat.R")
        shell: Rscript {0}
